/**
 * Tax export formatters for KeepKey Vault v11.
 *
 * Converts ReportData (generated by reports.ts) into:
 *   - CoinTracker CSV
 *   - ZenLedger CSV
 *
 * Transaction data is extracted from the "Transaction Details" or
 * "Transaction History" sections stored in the report.
 */

import type { ReportData, ReportSection } from '../shared/types'

// ── Internal canonical transaction model ────────────────────────────

export type TaxTxType =
	| 'transfer'
	| 'swap'
	| 'buy'
	| 'sell'
	| 'staking_reward'
	| 'mining_reward'
	| 'airdrop'
	| 'fee'

export interface TaxTransaction {
	id: string
	timestamp: string   // ISO-8601 UTC  e.g. "2024-01-01 14:33:10"
	txHash: string
	type: TaxTxType
	assetSent: string
	amountSent: number
	assetReceived: string
	amountReceived: number
	feeAsset: string
	feeAmount: number
	fromAddress: string
	toAddress: string
	notes: string
}

// ── Extract transactions from ReportData ────────────────────────────

/**
 * Parse BTC transaction data from report sections.
 *
 * Prefers "Transaction Details" table (has From/To columns) over
 * "Transaction History" table (lacks address columns).
 */
export function extractTransactionsFromReport(data: ReportData): TaxTransaction[] {
	const txs: TaxTransaction[] = []

	// Find the detailed transaction table first (has From/To)
	let txSection = data.sections.find(
		s => s.type === 'table' && s.title.startsWith('Transaction Details'),
	)
	let useDetailed = true

	// Fallback to Transaction History (less detail)
	if (!txSection) {
		txSection = data.sections.find(
			s => s.type === 'table' && s.title.startsWith('Transaction History'),
		)
		useDetailed = false
	}

	if (!txSection || txSection.type !== 'table') return txs

	const rows = txSection.data.rows || []
	const headers = txSection.data.headers || []

	for (const row of rows) {
		if (useDetailed) {
			// Transaction Details: [TXID, Dir, Block, Date, Value (BTC), Fee (BTC), From, To]
			const txid = cleanTxid(String(row[0] || ''))
			const dir = String(row[1] || '').toLowerCase()
			const date = String(row[3] || '')
			const value = parseNum(row[4])
			const fee = parseNum(row[5])
			const from = String(row[6] || '')
			const to = String(row[7] || '')

			txs.push(buildBtcTx(txid, dir, date, value, fee, from, to))
		} else {
			// Transaction History: [#, Dir, TXID, Block, Date, Value (BTC), Fee (BTC)]
			const txid = cleanTxid(String(row[2] || ''))
			const dir = String(row[1] || '').toLowerCase()
			const date = String(row[4] || '')
			const value = parseNum(row[5])
			const fee = parseNum(row[6])

			txs.push(buildBtcTx(txid, dir, date, value, fee, '', ''))
		}
	}

	return txs
}

function cleanTxid(txid: string): string {
	return txid.replace(/\.+$/, '')  // strip trailing ".." from truncation
}

function parseNum(val: any): number {
	const n = parseFloat(String(val ?? '0'))
	return isNaN(n) ? 0 : n
}

function buildBtcTx(
	txid: string, dir: string, date: string,
	value: number, fee: number,
	from: string, to: string,
): TaxTransaction {
	const isReceived = dir === 'received'
	return {
		id: txid,
		timestamp: normalizeTimestamp(date),
		txHash: txid,
		type: 'transfer',
		assetSent: isReceived ? '' : 'BTC',
		amountSent: isReceived ? 0 : value,
		assetReceived: isReceived ? 'BTC' : '',
		amountReceived: isReceived ? value : 0,
		feeAsset: fee > 0 ? 'BTC' : '',
		feeAmount: fee,
		fromAddress: from,
		toAddress: to,
		notes: '',
	}
}

/** Normalize date strings to "YYYY-MM-DD HH:MM:SS" format accepted by tax software */
function normalizeTimestamp(date: string): string {
	if (!date || date === 'Pending') return ''
	// Already in "2024-01-01 14:33:10" format from report
	if (/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(date)) return date
	// ISO format "2024-01-01T14:33:10Z" → "2024-01-01 14:33:10"
	if (/^\d{4}-\d{2}-\d{2}T/.test(date)) return date.replace('T', ' ').replace('Z', '').substring(0, 19)
	return date
}

// ── CSV safety ──────────────────────────────────────────────────────

/** Escape a cell value for CSV: quote wrapping + formula injection prevention */
function csvCell(value: any): string {
	let s = String(value ?? '').replace(/"/g, '""')
	const trimmed = s.trimStart()
	if (/^[=+\-@\t\r\n]/.test(trimmed)) s = `'${s}`
	return `"${s}"`
}

// ── CoinTracker CSV ─────────────────────────────────────────────────

const COINTRACKER_HEADERS = [
	'Date',
	'Received Quantity',
	'Received Currency',
	'Sent Quantity',
	'Sent Currency',
	'Fee Amount',
	'Fee Currency',
	'Tag',
]

function coinTrackerTag(tx: TaxTransaction): string {
	switch (tx.type) {
		case 'swap': return 'trade'
		case 'buy': return 'trade'
		case 'sell': return 'trade'
		case 'staking_reward': return 'staking'
		case 'mining_reward': return 'mining'
		case 'airdrop': return 'airdrop'
		case 'fee': return 'withdrawal'
		case 'transfer':
		default: {
			if (tx.amountReceived > 0 && tx.amountSent === 0) return 'deposit'
			if (tx.amountSent > 0 && tx.amountReceived === 0) return 'withdrawal'
			if (tx.amountSent > 0 && tx.amountReceived > 0) return 'trade'
			return 'transfer'
		}
	}
}

export function toCoinTrackerCsv(txs: TaxTransaction[]): string {
	const lines: string[] = []
	lines.push(COINTRACKER_HEADERS.join(','))

	for (const tx of txs) {
		if (!tx.timestamp) continue  // skip pending
		lines.push([
			csvCell(tx.timestamp),
			tx.amountReceived > 0 ? csvCell(tx.amountReceived) : csvCell(''),
			tx.assetReceived ? csvCell(tx.assetReceived) : csvCell(''),
			tx.amountSent > 0 ? csvCell(tx.amountSent) : csvCell(''),
			tx.assetSent ? csvCell(tx.assetSent) : csvCell(''),
			tx.feeAmount > 0 ? csvCell(tx.feeAmount) : csvCell(''),
			tx.feeAsset ? csvCell(tx.feeAsset) : csvCell(''),
			csvCell(coinTrackerTag(tx)),
		].join(','))
	}

	return lines.join('\n')
}

// ── ZenLedger CSV ───────────────────────────────────────────────────

const ZENLEDGER_HEADERS = [
	'Timestamp',
	'Transaction Type',
	'Base Currency',
	'Base Amount',
	'Quote Currency',
	'Quote Amount',
	'Fee Currency',
	'Fee Amount',
	'Exchange',
	'Transaction ID',
]

function zenLedgerType(tx: TaxTransaction): string {
	switch (tx.type) {
		case 'swap': return 'trade'
		case 'buy': return 'trade'
		case 'sell': return 'trade'
		case 'staking_reward': return 'income'
		case 'mining_reward': return 'mining'
		case 'airdrop': return 'airdrop'
		case 'fee': return 'spend'
		case 'transfer':
		default: {
			if (tx.amountReceived > 0 && tx.amountSent === 0) return 'deposit'
			if (tx.amountSent > 0 && tx.amountReceived === 0) return 'withdrawal'
			if (tx.amountSent > 0 && tx.amountReceived > 0) return 'trade'
			return 'transfer'
		}
	}
}

export function toZenLedgerCsv(txs: TaxTransaction[]): string {
	const lines: string[] = []
	lines.push(ZENLEDGER_HEADERS.join(','))

	for (const tx of txs) {
		if (!tx.timestamp) continue  // skip pending
		lines.push([
			csvCell(tx.timestamp),
			csvCell(zenLedgerType(tx)),
			tx.assetReceived ? csvCell(tx.assetReceived) : csvCell(''),
			tx.amountReceived > 0 ? csvCell(tx.amountReceived) : csvCell(''),
			tx.assetSent ? csvCell(tx.assetSent) : csvCell(''),
			tx.amountSent > 0 ? csvCell(tx.amountSent) : csvCell(''),
			tx.feeAsset ? csvCell(tx.feeAsset) : csvCell(''),
			tx.feeAmount > 0 ? csvCell(tx.feeAmount) : csvCell(''),
			csvCell('KeepKey'),
			csvCell(tx.txHash),
		].join(','))
	}

	return lines.join('\n')
}
