#!/usr/bin/env bash
# Build a universal macOS libkkemu.dylib from the firmware commit pinned by
# this Vault checkout. The universal binary is required because CI derives the
# Intel app from the arm64 app archive after Electrobun packaging.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FW_DIR="$REPO_ROOT/modules/keepkey-firmware"
STAGE_DIR="$REPO_ROOT/projects/keepkey-vault/emulator-bundle"
EXPECTED_VERSION="${EMU_EXPECTED_VERSION:-7.16.0}"
PROTOC_WRAPPER="$REPO_ROOT/scripts/protoc-nanopb-compat.sh"
PROTOC_VERSION=21.12
TC_CACHE="$HOME/.keepkey/emulator/.toolchain"

[ "$(uname -s)" = Darwin ] || { echo "ERROR: macOS emulator build requires macOS"; exit 1; }
command -v cmake >/dev/null || { echo "ERROR: cmake is required"; exit 1; }
command -v lipo >/dev/null || { echo "ERROR: lipo is required"; exit 1; }

SOURCE_VERSION="$(awk '$1 == "VERSION" { print $2; exit }' "$FW_DIR/CMakeLists.txt")"
[ "$SOURCE_VERSION" = "$EXPECTED_VERSION" ] || {
  echo "ERROR: firmware source is $SOURCE_VERSION; release requires $EXPECTED_VERSION"; exit 1; }
PINNED_SHA="$(git -C "$REPO_ROOT" ls-tree HEAD modules/keepkey-firmware | awk '{print $3}')"
SOURCE_SHA="$(git -C "$FW_DIR" rev-parse HEAD)"
[ "$SOURCE_SHA" = "$PINNED_SHA" ] || {
  echo "ERROR: firmware checkout $SOURCE_SHA does not match Vault gitlink $PINNED_SHA"; exit 1; }

if [ -n "${EMU_PYTHON:-}" ]; then
  PYTHON="$(command -v "$EMU_PYTHON")"
elif [ -x "$HOME/.pyenv/versions/3.10.15/bin/python" ]; then
  PYTHON="$HOME/.pyenv/versions/3.10.15/bin/python"
else
  PYTHON="$(command -v python3)"
fi
"$PYTHON" - <<'PY'
from importlib.metadata import version
import google.protobuf
assert version('nanopb') == '0.3.9.4.post3', version('nanopb')
assert google.protobuf.__version__ == '3.20.3', google.protobuf.__version__
PY

PYBIN="$(dirname "$PYTHON")"
NANOPB_DIR="$("$PYTHON" -c 'import os,nanopb;print(os.path.dirname(nanopb.__file__))')"
if [ -n "${EMU_PROTOC:-}" ]; then
  REAL_PROTOC="$(command -v "$EMU_PROTOC")"
else
  REAL_PROTOC="$TC_CACHE/protoc-$PROTOC_VERSION/bin/protoc"
  if [ ! -x "$REAL_PROTOC" ]; then
    case "$(uname -m)" in
      arm64) asset="protoc-$PROTOC_VERSION-osx-aarch_64.zip" ;;
      x86_64) asset="protoc-$PROTOC_VERSION-osx-x86_64.zip" ;;
      *) echo "ERROR: unsupported macOS architecture $(uname -m)"; exit 1 ;;
    esac
    archive="$(mktemp -t kk-protoc).zip"
    mkdir -p "$TC_CACHE/protoc-$PROTOC_VERSION"
    curl -sSL -fL -o "$archive" \
      "https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/$asset"
    unzip -oq "$archive" -d "$TC_CACHE/protoc-$PROTOC_VERSION"
    rm -f "$archive"
    chmod +x "$REAL_PROTOC"
  fi
fi
export KK_REAL_PROTOC="$REAL_PROTOC"
chmod +x "$PROTOC_WRAPPER"

# The 0.3.9.4.post3 wheel on a fresh Python install can contain *_pb2.py files
# generated by a much newer protoc. They import protobuf.runtime_version, which
# does not exist in the pinned 3.20.3 runtime. Rebuild nanopb's own descriptors
# with our pinned protoc before invoking the plugin. This is idempotent and
# removes dependence on mutable wheel-generated files.
NANOPB_PROTO_DIR="$NANOPB_DIR/generator/proto"
( cd "$NANOPB_PROTO_DIR" && "$REAL_PROTOC" --python_out=. nanopb.proto plugin.proto )
"$PYTHON" -c 'from nanopb.generator.proto import nanopb_pb2, plugin_pb2'

echo "=== Firmware $SOURCE_VERSION ($SOURCE_SHA) ==="
echo "    protoc: $($REAL_PROTOC --version)"
CPU_COUNT="$(sysctl -n hw.ncpu 2>/dev/null || getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)"

build_arch() {
  local arch="$1"
  local build_dir="$FW_DIR/build-emu-macos-$arch"
  rm -rf "$build_dir"
  PATH="$PYBIN:$PATH:$NANOPB_DIR/generator" cmake -S "$FW_DIR" -B "$build_dir" \
    -DKK_EMULATOR=ON -DKK_DEBUG_LINK=ON -DKK_BUILD_DYLIB=ON \
    -DKK_CLEARSIGN_ALPHA_ROOT=ON \
    -DCMAKE_OSX_ARCHITECTURES="$arch" \
    -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DPROTOC_BINARY="$PROTOC_WRAPPER" \
    -DNANOPB_DIR="$NANOPB_DIR" \
    -DCMAKE_C_FLAGS="-DPB_NO_PACKED_STRUCTS=1" \
    -DCMAKE_CXX_FLAGS="-DPB_NO_PACKED_STRUCTS=1"
  grep -qx 'KK_CLEARSIGN_ALPHA_ROOT:BOOL=ON' "$build_dir/CMakeCache.txt" || {
    echo "ERROR: $arch emulator was configured without the ClearSign alpha root"; exit 1; }
  PATH="$PYBIN:$PATH:$NANOPB_DIR/generator" cmake --build "$build_dir" \
    --target kkemulator_dylib -j"$CPU_COUNT"
  test -f "$build_dir/lib/libkkemu.dylib" || {
    echo "ERROR: $arch libkkemu.dylib missing"; exit 1; }
}

build_arch arm64
build_arch x86_64

mkdir -p "$STAGE_DIR"
lipo -create \
  "$FW_DIR/build-emu-macos-arm64/lib/libkkemu.dylib" \
  "$FW_DIR/build-emu-macos-x86_64/lib/libkkemu.dylib" \
  -output "$STAGE_DIR/libkkemu.dylib"
codesign --force --sign - "$STAGE_DIR/libkkemu.dylib"

archs="$(lipo -archs "$STAGE_DIR/libkkemu.dylib")"
for arch in arm64 x86_64; do
  grep -qw "$arch" <<<"$archs" || { echo "ERROR: universal dylib missing $arch"; exit 1; }
done

required_symbols=(
  kkemu_init kkemu_shutdown kkemu_write kkemu_read kkemu_poll
  kkemu_is_running kkemu_pop_frame kkemu_start kkemu_stop
  kkemu_lock kkemu_unlock kkemu_trylock
)
exports="$(nm -gU "$STAGE_DIR/libkkemu.dylib")"
for symbol in "${required_symbols[@]}"; do
  grep -Eq "[[:space:]]_${symbol}$" <<<"$exports" || {
    echo "ERROR: universal dylib is missing required FFI export $symbol"; exit 1; }
done

echo "=== SUCCESS: staged $STAGE_DIR/libkkemu.dylib ==="
echo "    Architectures: $archs"
echo "    ABI: ${#required_symbols[@]} required exports present"
echo "    ClearSign alpha root: ON"
