#!/usr/bin/env bash
# Cross-compile the Windows emulator DLL (libkkemu.dll) from this macOS/Linux
# host using MinGW-w64. Produces the SAME 12-symbol FFI library the vault loads
# on macOS (libkkemu.dylib) — just as a Windows .dll.
#
#   ┌───────────────────────────────────────────────────────────────────┐
#   │ This is NOT the emulator used in firmware CI.                        │
#   │   • firmware CI builds the standalone UDP `kkemu` binary (sockets,   │
#   │     :11044/:11045) for python-keepkey tests + OLED screenshots.      │
#   │   • THIS builds libkkemu.dll — the in-process, ring-buffer FFI lib   │
#   │     the vault loads via bun:ffi (the .dll sibling of .dylib/.so).    │
#   └───────────────────────────────────────────────────────────────────┘
#
# Invoke via `make build-emulator-windows` (preferred). Requires MinGW-w64:
#   macOS:  brew install mingw-w64
#   Linux:  apt-get install mingw-w64
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FW_DIR="$REPO_ROOT/modules/keepkey-firmware"
BUILD_DIR="$FW_DIR/build-emu-win"
TOOLCHAIN_FILE="cmake/toolchains/mingw-w64-x86_64.cmake"
TC_CACHE="$HOME/.keepkey/emulator/.toolchain"
PROTOC_VERSION=21.12
EXPECTED_VERSION="${EMU_EXPECTED_VERSION:-7.16.0}"
STAGE_DIR="$REPO_ROOT/projects/keepkey-vault/emulator-bundle"
PROTOC_WRAPPER="$REPO_ROOT/scripts/protoc-nanopb-compat.sh"

SOURCE_VERSION="$(awk '$1 == "VERSION" { print $2; exit }' "$FW_DIR/CMakeLists.txt")"
[ "$SOURCE_VERSION" = "$EXPECTED_VERSION" ] || {
  echo "ERROR: firmware source is $SOURCE_VERSION; release requires $EXPECTED_VERSION"; exit 1; }
PINNED_SHA="$(git -C "$REPO_ROOT" ls-tree HEAD modules/keepkey-firmware | awk '{print $3}')"
SOURCE_SHA="$(git -C "$FW_DIR" rev-parse HEAD)"
[ "$SOURCE_SHA" = "$PINNED_SHA" ] || {
  echo "ERROR: firmware checkout $SOURCE_SHA does not match Vault gitlink $PINNED_SHA"; exit 1; }

echo "=== Windows emulator DLL cross-compile ==="
command -v x86_64-w64-mingw32-gcc >/dev/null 2>&1 || {
  echo "ERROR: x86_64-w64-mingw32-gcc not found. Install: brew install mingw-w64"; exit 1; }
echo "    MinGW:  $(x86_64-w64-mingw32-gcc --version | head -1)"

# --- Pinned host build toolchain (matches firmware CI dylib job) -------------
# protobuf 3.20.3 + nanopb 0.3.9.4 run under Python 3.10; protoc is pinned to
# 3.21.x so generated descriptors match the 3.20 runtime. CI supplies Python
# through actions/setup-python; local builds may use the established pyenv.
if [ -n "${EMU_PYTHON:-}" ]; then
  PYTHON="$(command -v "$EMU_PYTHON")"
elif [ -x "$HOME/.pyenv/versions/3.10.15/bin/python" ]; then
  PYTHON="$HOME/.pyenv/versions/3.10.15/bin/python"
else
  PYTHON="$(command -v python3)"
fi
"$PYTHON" - <<'PY'
from importlib.metadata import version
import google.protobuf
assert version('nanopb') == '0.3.9.4.post3', version('nanopb')
assert google.protobuf.__version__ == '3.20.3', google.protobuf.__version__
PY
PYBIN="$(dirname "$PYTHON")"
NANOPB_GEN_DIR="$("$PYTHON" -c 'import os,nanopb;print(os.path.dirname(nanopb.__file__))')/generator"

# Fetch pinned protoc once (cached). osx-aarch_64 / linux-x86_64.
PROTOC_BIN="$TC_CACHE/protoc-$PROTOC_VERSION/bin/protoc"
if [ ! -x "$PROTOC_BIN" ]; then
  case "$(uname -s)-$(uname -m)" in
    Darwin-arm64) ASSET="protoc-$PROTOC_VERSION-osx-aarch_64.zip" ;;
    Darwin-x86_64) ASSET="protoc-$PROTOC_VERSION-osx-x86_64.zip" ;;
    Linux-x86_64) ASSET="protoc-$PROTOC_VERSION-linux-x86_64.zip" ;;
    *) echo "ERROR: no pinned protoc asset for $(uname -s)-$(uname -m)"; exit 1 ;;
  esac
  echo "    Fetching pinned protoc $PROTOC_VERSION ($ASSET)..."
  mkdir -p "$TC_CACHE/protoc-$PROTOC_VERSION"
  curl -sSL -fL -o /tmp/protoc-pin.zip \
    "https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOC_VERSION/$ASSET"
  unzip -oq /tmp/protoc-pin.zip -d "$TC_CACHE/protoc-$PROTOC_VERSION"
  chmod +x "$PROTOC_BIN"
fi
echo "    protoc: $("$PROTOC_BIN" --version)"

export PATH="$(dirname "$PROTOC_BIN"):$PYBIN:$NANOPB_GEN_DIR:$PATH"
NANOPB_DIR="$("$PYTHON" -c 'import os,nanopb;print(os.path.dirname(nanopb.__file__))')"
NANOPB_PLUGIN="$(command -v protoc-gen-nanopb)"
export KK_REAL_PROTOC="$PROTOC_BIN"
chmod +x "$PROTOC_WRAPPER"

# A fresh 0.3.9.4.post3 wheel may ship descriptors generated by a much newer
# protoc, incompatible with protobuf 3.20.3. Normalize them with the same
# pinned protoc used for the firmware messages before loading the plugin.
NANOPB_PROTO_DIR="$NANOPB_DIR/generator/proto"
( cd "$NANOPB_PROTO_DIR" && "$PROTOC_BIN" --python_out=. nanopb.proto plugin.proto )
"$PYTHON" -c 'from nanopb.generator.proto import nanopb_pb2, plugin_pb2'

# --- Configure + build only the dylib target --------------------------------
echo "=== Firmware $SOURCE_VERSION ($SOURCE_SHA) ==="
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"
( cd "$FW_DIR" && cmake -S . -B build-emu-win \
    -DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN_FILE" \
    -DKK_EMULATOR=ON -DKK_DEBUG_LINK=ON -DKK_BUILD_DYLIB=ON \
    -DKK_CLEARSIGN_ALPHA_ROOT=ON \
    -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DPROTOC_BINARY="$PROTOC_WRAPPER" \
    -DNANOPB_DIR="$NANOPB_DIR" -DNANOPB_PLUGIN="$NANOPB_PLUGIN" \
    -DCMAKE_C_FLAGS="-DPB_NO_PACKED_STRUCTS=1" \
    -DCMAKE_CXX_FLAGS="-DPB_NO_PACKED_STRUCTS=1" )

grep -qx 'KK_CLEARSIGN_ALPHA_ROOT:BOOL=ON' "$BUILD_DIR/CMakeCache.txt" || {
  echo "ERROR: Windows emulator was configured without the ClearSign alpha root"; exit 1; }

( cd "$FW_DIR" && cmake --build build-emu-win --target kkemulator_dylib -j"$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)" )

DLL="$(find "$BUILD_DIR" -name 'libkkemu.dll' -o -name 'kkemu.dll' | head -1)"
if [ -n "$DLL" ] && [ -f "$DLL" ]; then
  required_symbols=(
    kkemu_init kkemu_shutdown kkemu_write kkemu_read kkemu_poll
    kkemu_is_running kkemu_pop_frame kkemu_start kkemu_stop
    kkemu_lock kkemu_unlock kkemu_trylock
  )
  exports="$(x86_64-w64-mingw32-nm -g --defined-only "$DLL")"
  for symbol in "${required_symbols[@]}"; do
    grep -Eq "[[:space:]]${symbol}$" <<<"$exports" || {
      echo "ERROR: $DLL is missing required FFI export $symbol"; exit 1; }
  done

  imports="$(x86_64-w64-mingw32-objdump -p "$DLL" | sed -n 's/^[[:space:]]*DLL Name: //p')"
  while IFS= read -r import; do
    lower_import="$(printf '%s' "$import" | tr '[:upper:]' '[:lower:]')"
    case "$lower_import" in
      bcrypt.dll|kernel32.dll|api-ms-win-crt-*.dll) ;;
      *) echo "ERROR: unbundled Windows runtime dependency: $import"; exit 1 ;;
    esac
  done <<<"$imports"

  mkdir -p "$STAGE_DIR"
  cp "$DLL" "$STAGE_DIR/libkkemu.dll"
  echo "=== SUCCESS: staged $STAGE_DIR/libkkemu.dll ==="
  echo "    ABI: ${#required_symbols[@]} required exports present"
  echo "    Imports: Windows system DLLs only"
  echo "    ClearSign alpha root: ON"
else
  echo "=== FAILED: no libkkemu.dll produced ==="; exit 1
fi
